server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://elastic-query-service/elastic-query-service/documents'
    service-id: elastic-query-service
    instances:
      -
        id: elastic-query-service-1
        host: localhost
        port: 8183
#      - id: elastic-query-service-2
#        host: localhost
#        port: 8185
  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client'
            client-secret: '{cipher}548cc33f460370948abe90e8f6c9f21d9d7ef5c7dbd2ab6dfaf8f86ab5b5f6b6cd943876ce6214192d130f41d7943b9f557b5d260972e47eb09845e1c70a979c'
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:9091/auth/realms/microservices-realm

security:
  logout-success-url: http://localhost:8184/elastic-query-web-client
  default-client-registration-id: keycloak

user-config:
  username: test
  password: '{cipher}4a683645fc7452172f9f11ea78203a63f4219d9bad5d709e70fd2d2d2cf2d0da'
  roles: USER